name: Test
run-name: Test ${{ github.ref }}

on: pull_request

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    container:
      image: swift:6.1.0
    steps:
      - uses: actions/checkout@v4
      - run: swift test
